---
title: "11finaldata-ld"
author: "Rimjhim Saxena"
date: "2023-03-04"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(dplyr)
library(tidyverse)

a = read.csv("~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/04Append/nss_43_51_56_57_63_66.csv")

klems = read.csv("~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/EXTRA/NIC98-Sector-Exposure.csv")

klems_long = klems %>% 
  pivot_longer(cols = c(caplab_1987,caplab_1994,caplab_2000,caplab_2001,caplab_2006,caplab_2009),
               names_to = "year",
               values_to = "caplab")

klems_long = klems_long %>% 
  mutate(round = case_when(year=="caplab_1987" ~ 43,
                           year=="caplab_1994" ~ 51,
                           year=="caplab_2000" ~ 56,
                           year=="caplab_2001" ~ 57,
                           year=="caplab_2006" ~ 63,
                           year=="caplab_2009" ~ 66))

names(klems_long)[1] = "NIC98_Group"

klems_long = klems_long[,-c(2:6)]

a$NIC98_Group = sprintf("%02d",a$NIC98_Group)
klems_long$NIC98_Group = sprintf("%02d",klems_long$NIC98_Group)

a = merge(a,klems_long,by=c("NIC98_Group","round"))

#write.csv(a,"~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/04Append/nss_43_51_56_57_63_66_klems.csv",row.names = F)


a = a[,-c(1,17:19,25:36)] # removing NIC 70, NIC 87, NIC 98, NIC98_Group, All State Districts Except 72
geog = a[,c(20,3:5,7)] # only StateDistrict_72, Sector, State_Region, State, District
subround = a[,c(20,2,6,1)] # Only HHID, SubRound, StateDistrict_72, Round

# Not all districts had all surveys done in one sub round
# Therefore there will be variation in temperature within district
# Gotta rethink following data aggregation - Maybe just need to add temperature by subgroup 
round_ag = subround %>% 
  group_by(round,SubRound,State_District_72) %>% 
  summarise(total = n())
```



Aggregate data 
```{r}

#Mean averages of a lot of variables 
b = a %>% 
  group_by(State_District_72,Job_Sector,round) %>% 
  summarise(mpce = mean(mpce,na.rm = T),
            food_month = mean(foodexp_monthly,na.rm = T),
            clothing_annual = mean(clothing_annual,na.rm = T),
            goodservice_month = mean(GoodsServicesExp_monthly,na.rm = T),
            eduhealth_annual = mean(EduHealth_annual,na.rm = T),
            caplab = mean(caplab,na.rm = T),
            total = n())

#Finding total count of households in each district to calculate shares
c = a %>% 
  group_by(State_District_72,round) %>% 
  summarise(freq= n())


d = merge(b,c,by=c("State_District_72","round"),all.x = T)
d$share = round((d$total/d$freq)*100,2)
d$Exposure = ifelse(d$Job_Sector=="Service","Insular","Exposed")

e = a %>% 
  group_by(State_District_72,round,Exposure) %>% 
  summarise(tot_exposure = n())

f = merge(d,e,by=c("State_District_72","round","Exposure"))

```

adding geog to data

```{r}
g = merge(f,geog,by=c("State_District_72"))
g$newid = paste0(g$State_District_72,g$round,g$Job_Sector)
g = g[!duplicated(g$newid),]
g = g[,-c(19)]
```


Aggregating data for long difference 

```{r}
a$ld = ifelse(a$round<=56,0,1)

#Mean averages of a lot of variables 
h = a %>% 
  group_by(State_District_72,Job_Sector,ld) %>% 
  summarise(mpce = mean(mpce,na.rm = T),
            food_month = mean(foodexp_monthly,na.rm = T),
            clothing_annual = mean(clothing_annual,na.rm = T),
            goodservice_month = mean(GoodsServicesExp_monthly,na.rm = T),
            eduhealth_annual = mean(EduHealth_annual,na.rm = T),
            caplab = mean(caplab,na.rm = T),
            total = n())

i = a %>% 
  group_by(State_District_72,ld) %>% 
  summarise(freq= n())


j = merge(h,i,by=c("State_District_72","ld"),all.x = T)
j$share = round((d$total/d$freq)*100,2)
j$Exposure = ifelse(d$Job_Sector=="Service","Insular","Exposed")

k = a %>% 
  group_by(State_District_72,ld,Exposure) %>% 
  summarise(tot_exposure = n())

l = merge(j,k,by=c("State_District_72","ld","Exposure"))

m = merge(l,geog,by=c("State_District_72"))
m$newid = paste0(m$State_District_72,m$ld,m$Job_Sector)
m = m[!duplicated(m$newid),]
m = m[,-c(19)]
```

Writing data
```{r}
write.csv(f,"~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/06Final/final-data.csv",row.names = F)
write.csv(g,"~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/06Final/final-wgeog.csv",row.names = F)
write.csv(m,"~/OneDrive - UCB-O365/01CURRENT/Structural Transformation Climate Change India/Data/06Final/final-wgeog-ld.csv",row.names = F)

```

